### ISSUE TITLE
Display accelerated ALBA instance per vPool on Storage Router Detail page.

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1000]
Based upon https://github.com/openvstorage/framework/issues/735 it was made clear that there is no way to see which accelerated ALBA instance is used.  Add this to the Storage Router detail page next to vPool.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1130 --> openvstorage-2.7.5-rev.4273.d9bb7fb
https://github.com/openvstorage/framework-alba-plugin/pull/267 --> openvstorage-backend-1.7.5-rev.811.c1b83e6

**Comment by kvanhijf** [comment]
vPool overview page, shows information on the backend used
vPool detail page, shows information on the backend used
vPool detail page --> management actions shows information on the accelerated backend used / storagerouter

**Comment by JeffreyDevloo** [comment]
### Information

The vpool section has received a massive overhaul including the removal of certain parameters and a disk role.
Certain test cases should be thoroughly tested before we can close this ticket and #735 

##### Changes
- Removal of read role
- Vpool wizard automatically resolves backends (removal of reload button)
- vpool - backendtype relation removed
- vpool configuration changes

#### Test cases

##### Update to the latest revision

Primarily due to the removed roles and certain variables. The updated system should still be able to handle the flow well and the 'READ' roles on the disk should have been removed.

##### Parameter changes - API

The API should be able to handle both the old and the new variables. If this is the case that would mean that older automated installs can still be used to configure OVS.

The API to add a read roles will most likely break as the code will check an enum first (and the role got deleted in the enum)

##### GUI changes

The changes should have reflected in the gui. The requests on this and the linked ticket should have been implemented.

##### Impact on a global backend

Vpool parameter have changed. The possible impact on a global backend should be verified.

**Comment by kvanhijf** [comment]
@JeffreyDevloo : Just to be clear regarding the API, it should indeed still be possible to add a vpool using the old parameter layout, but ONLY FOR 2 <= API VERSION <= 5
As of API version 6, the new parameter layout is expected
