### ISSUE TITLE
Wizard "loading" icon is positioned wrong

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1104]
Introduced by #1053, the loading icon is positioned wrong.

**Comment by khenderick** [comment]
@JeffreyDevloo fixed this by #1105, packaged in openvstorage-2.7.4-rev.4232.a5868f8

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup latest cluster
- Added disk roles
- Added backend
- Checked vpool wizard

### Output

Loading icon is now displayed to the left of the buttons instead of the right. (The latter caused the buttons to shift when the loading popped up)

![screenshot from 2016-11-02 09-56-26](https://cloud.githubusercontent.com/assets/17570109/19922423/d5e94dd2-a0e2-11e6-8114-7ec317ac7eab.png)

### Test result

Test passed.

### Packages
- openvstorage                       2.7.4-rev.4251.b3a026a-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.801.33cbb60-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.801.33cbb60-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.801.33cbb60-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                  2.7.4-rev.4251.b3a026a-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.801.33cbb60-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.414.20eee54-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4251.b3a026a-1                                 amd64        openvStorage Web Applications
