### ISSUE TITLE
Mark halted volumes in the GUI

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1351]
### Problem description
All info about the volumes and vpool are lost when the volume is not running.

![selection_115](https://cloud.githubusercontent.com/assets/17570109/22027219/6f82c654-dcd3-11e6-9b4e-940f98d09c2a.png)
The volume in the screenshot also has 55GB of data stored. However because its down it reports 0.
A result of this is that the vpool reports less data than the backend currently has.

**Comment by wimpers** [comment]
I believe the reason why it is zero is because we directly fetch that data from the volumedriver. In case the volume is down the volumedriver returns zero. The framework has no knowledge about the stored data.

Some things we could do:
* Keep a value for the stored data (and other parameters) which gets updated daily. Don't think this is a good idea.
* Indicate clearly that the volume isn't started (all values 0 instead of some values filled in)
* have the voldrv return something the actual last value instead of 0 (if possible)

**Comment by wimpers** [comment]
If volume is halted , mark the volume with a red line in the GUI and put -  for the dynamic properties.

**Comment by wimpers** [comment]
The fact that the  vPool doesn't contain the stored amount isn't a problem.

**Comment by wimpers** [comment]
Original name of this ticket `Show volume information even when volume is down` renamed to `Mark halted volumes in the GUI`

**Comment by redlicha** [comment]
You need to differentiate between a *non-running* volume (restart failed for example, or problems during migration) and a *halted* volume (volume is running but will refuse I/O due to a grave error, e.g. fenced by another instance on another node or other fatal errors - these are signalled via voldrv events):
* non-running: `info_volume` or other calls directed at the volume will not be able to locate it and raise a `MaxRedirectsExceeded` exception
* halted: `info_volume` returns a volume information object whose `halted` member is `True`

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
All volumes will have status field similar to backend and vPools
This status field should be displayed on:
* vDisk overview page,
* vDisk detail page,
* vPool detail page - vDisk tab,
* StorageRouter detail page - vDisk tab

Following colors apply:
* Green: Running volumes
* Orange: Non-running volumes (See comment by Arne what non-running means)
* Red: Halted volumes (See comment by Arne what halted means)

Additional remarks:
* Non-running or halted volumes will no longer show following fields (A dash '-' is displayed instead)
  * Stored Data
  * IOPS
  * Read Speed
  * Write Speed
  * Number of snapshots

Additionally i've implemented this:
* New API to restart a volume (/vdisks/<guid>/restart')
```
def restart(self, vdisk, force=False):
```
* New button in GUI to restart a volume
  * Can only be used when volume is not RUNNING (so non-running or halted)

https://github.com/openvstorage/framework/pull/1394  --> openvstorage-2.7.11-dev.1485960176.10850d4
https://github.com/openvstorage/framework-alba-plugin/pull/352 --> openvstorage-backend-1.7.11-dev.1485960239.26b33e6

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/450
