### ISSUE TITLE
DTL role for storage router disk management

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1372]
Currently the DTL is on the same disk as the write buffer. Add another role DTL to assign the DTL role to an SSD. There should be 1 and only 1 disk with a DTL role.

**Comment by wimpers** [comment]
@kenneth How much work would this be? Can you provide a rough estimate?

**Comment by wimpers** [comment]
Open question:
Should be there be 1 and only 1 disk with a DTL role? Since each vpool has its own DTL process, it might be good to round robin across multiple DTL disks? @saelbrec  wdyt?

**Comment by khenderick** [comment]
@wimpers, shouldn't take more than a few days

**Comment by khenderick** [comment]
Set to `state_question`. No need to start this one with open questions.

Extra question: Do we want to support extending a vPool to a node without a DTL role (e.g. not having a DTL server at that point)

**Comment by saelbrec** [comment]
Q1: Should there be 1 and only 1 disk with a DTL role? Since each vpool has its own DTL process, it might be good to round robin across multiple DTL disks
Agree, it makes sense to support multiple DTL roles from which can be chosen when the vpool is added/extended. Multiple DTL processes for a given vpool on one and the same node is however not required.

Q2: Do we want to support extending a vPool to a node without a DTL role (e.g. not having a DTL server at that point)
In theory this is possible and would be the most flexible, but it's also dangerous as people not knowing the details of the storage system could end up in a unbalanced setup where the number and capacity of the DTL's is too far off with the volumedrivers being deployed in the same vpool and as such introducing performance issues. I would suggest to stick to a configuration where we always deploy a DTL on the node to which a vpool is added or extended. IOW, the DTL role becomes mandatory.

@khenderick ,
Can we implement it so that the DTL can get deployed using it's own control (and maybe API)?

**Comment by khenderick** [comment]
@saelbrec, while it can be done in theory, it needs more work to actually make it useful. I'd suggest to create a separate ticket once we need it.

**Comment by saelbrec** [comment]
k, fine by me.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
A new required DTL role has been introduced. When creating/extending a vPool, the StorageRouter on which you wish to create/extend must have (and can only have) 1 DTL role

https://github.com/openvstorage/framework/pull/1387 --> openvstorage-2.7.11-dev.1485873245.cd485ed

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/453

**Comment by JeffreyDevloo** [comment]
### Information
The DTL role has been a prerequisite for our vpool test which also deploys a vdisk to write data upon it. DTL has been covered by the basic and advanced dtl test. These have been in the flow with the DTL role.
Changes that have been done on our side for implementing:
- https://github.com/openvstorage/automation-lib/pull/34/
- https://github.com/openvstorage/setups/pull/29
