### ISSUE TITLE
Creating and deleting a vdisk with the same devicename in a loop is asking for trouble

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1390]
### Problem description
Creating and deleting the same vdisk (with identical name and thus identical devicename) is asking for trouble. 
The current issues that this flow produces is:
- Stale metadata:
Disks that are present in DAL but not there in reality. You can see this easily when there is no more storage_id or storagerouter information 
(![screenshot from 2017-01-31 16-10-42](https://cloud.githubusercontent.com/assets/17570109/22470515/d93f67c6-e7cf-11e6-8067-c56ed389e5d3.png))
- FileExistsError
```
olumedriverfs::FileExistsException
std::exception::what: Path already exists /ovs-healthcheck-test-hS0fSZMDa6jOOoht3.raw File exists (17)
```
After a while, you can no longer fetch the vdisk information using  get_by_devicename. The method just returns None. However fetching the information via the GUI works perfectly. The cause of this is still unknown

**Comment by khenderick** [comment]
Basically creating a vDisk through the API will cause an event from the volumedriver to be processed. If celery can't cope with the amount of tasks, the events will be processed way too late. The thing is that a `devicename/vPool` combination unique is, and we assume that if we find one, we somehow missed a single event. We will then update that data object with all new information (including the `volume_id` of a volume that doesn't exist anymore) and will then try to sync it etc. That will fail since the `volume_id` doesn't exist anymore, and we'll remove the object from the model. So, in that case, we might have deleted a vDisk that was actually present. Anyway, all subsequent events will either delete or re-created the object in the model. 

Not sure whether this is the exact cause of the reported behavior, but it most likely an issue that will cause various strange things. So I'd rather fix that issue and see whether the reported was caused by (a side-effect of) this bug or not.

**Comment by khenderick** [comment]
@JeffreyDevloo, we might however add this as a test to make sure we can handle this scenario in the future.

**Comment by khenderick** [comment]
Fixed by #1396, packaged on dev in openvstorage-2.7.12-dev.1486374024.de8e760

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
Validation via:
https://github.com/openvstorage/integrationtests/pull/421

@JeffreyDevloo @kinvaris , pls review and merge this test in pls

**Comment by JeffreyDevloo** [comment]
### Validation
Test introduced by https://github.com/openvstorage/integrationtests/pull/421 no longer fails on
- Fargo
- Unstable
- Development
- Staging

Therefore I am closing this ticket

### Test result
Test passed.
