### ISSUE TITLE
Update should be able to handle certain partial failures

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1398]
Update should be able to handle certain partial failures.

If e.g. all components are selected and the install of one of the non-framework packages fails, the update is aborted and the services are restarted. This might reveal a non-working state since e.g. framework migrations have not been executed at that point.

A better approach would be that in such case, it still tries to finish the framework update, so at least the update can be re-tried using the GUI.

**Comment by wimpers** [comment]
From @khenderick : ballpark estimate 3-6 days.

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework/issues/1401

https://github.com/openvstorage/framework/pull/1418 --> openvstorage-2.7.12-dev.1486462862.1a65dc7
https://github.com/openvstorage/alba-asdmanager/pull/220 --> openvstorage-sdm-1.6.12-dev.1486463014.a549aab
https://github.com/openvstorage/framework-alba-plugin/pull/357 --> openvstorage-backend-1.7.12-dev.1486462938.eabfc67

**Comment by khenderick** [comment]
openvstorage-2.7.12.1
openvstorage-backend-1.7.12.1
openvstorage-sdm-1.6.12.1
