### ISSUE TITLE
Introduce API to setup external Arakoon

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1466]
### Problem descriptions
Setting up your own arakoons can be done yet there is no API to actually do this. Please introduce the api calls.
API should:
- Determine if its add or extend
- Restart_cluster_add so it is usable

**Comment by khenderick** [comment]
There is so much wrong with this request to be honest. That kinda sounds like you want to use the framework to setup arakoons that it should not manage afterwards. So most likely, you would use this to create clusters and then force the framework to use these instead of setting up its own clusters.

So the net profit is that you just shifted the responsibility of maintaining these services out of the framework. Why not request a feature that you can have a more fine graded control about what nodes should run arakoons (instead of just "master" and "extra"). Then the framework can automatically extend and maintain all arakoons, and you don't have to basically write a second framework.

**Comment by wimpers** [comment]
@JeffreyDevloo what is your issue exactly? What do you want to achieve? Where does this request come from?

**Comment by JeffreyDevloo** [comment]
Internally for QA we are currently building around the framework with our own framework which utilizes the API that the framework provides. However for the external arakoons (which is a supported case) we need to build this logic from the ground up ourselves. It would be wiser imo to either provide the API (let the fwk team decide how it should be handled) or to not support external arakoon setups.

**Comment by wimpers** [comment]
Can't you use the framework controller to install that Arakoon? If not maybe remove the blocking stuff there. Why does it need to be an API.

We don't want to extend our API to setup an external managed Arakoon. The definition of external is exactly that the Framework should not care about that Arakoon.

**Comment by JeffreyDevloo** [comment]
The reason for our request for an API is so that we are constantly in sync with the framework with minimal effort.
This way we maximize our QA time instead of fixing our implementations of our controllers as we have done in the past
Changes that we currently need to follow the FWK:
- https://github.com/openvstorage/framework/pull/1465

**Comment by wimpers** [comment]
I see.  I believe a better solution would be that if the framework breaks the test, they fix the tests also (and not only their unit test).

**Comment by kvanhijf** [comment]
The framework doesn't break tests, we optimize them

**Comment by wimpers** [comment]
> The framework doesn't break tests, we optimize them

Thats is alternative QA-ing. If it the test turns from green to red you broke it, not optimised it.

**Comment by khenderick** [comment]
@wimpers, we don't care about anyone except the framework team for any backwards incompatible changes to controllers. That's internal framework logic and not meant to be used by any other party or team. We have a backwards compatible API for any third party integration just to make sure that we don't have to fix the code for anybody else (code that we might not even know about).

**Comment by wimpers** [comment]
We don't want to offer an APi to setup external Arakoons.
