### ISSUE TITLE
Sync of volumes of storagedriver and model periodically

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1490]
In continuation of https://github.com/openvstorage/framework/issues/1233
### Problem description
By not letting the framework schedule this sync as a task, we keep on dividing the team and push them to make their own framework around the flaws of another one

For example Ops is now required too:
- Parse output from the healthcheck (as it previously was the only way to detect stale metadata)
- Call the sync of the framework to remove this issue

Why make it this complicated? The healthcheck could still report the stale metadata to let Ops have the history but the framework can periodically clean this up itself.

We should strive forward to trusting each team in their implementations and strengthen the cohesion of all teams instead of pushing each team away from one another.

### Possible solution
- Implement the scheduled task
- Actually listen to developers and each team before issuing a judgement

**Comment by wimpers** [comment]
@JeffreyDevloo I'm really sorry but this makes no sense. Instead of fixing possible root causes, we will wipe it under the carpet . I don't see why OPS would need to build their own framework around it. What they shouldn't do is, take the output of the healthcheck parse it and call the sync button automatically and be done.  We need to make sure these out of sync model events don't happen!

I don't see why the current approach pushes teams away from each other but I'd like to discuss that whenever you have time.

Next, I'm also interested in how many times this occurs. or it happens frequently and  then we have a serious problem or it happens very, very occasionally in which OPS care might, open for discussion, be better than automatic fixing.

**Comment by wimpers** [comment]
Possible consensus: have the framework automatic fix the issue but raise an error in the log for monitoring. This way it is fixed fast and OPS can still investigate.

**Comment by wimpers** [comment]
See questions in my long comment. #times it happens etc ...

**Comment by JeffreyDevloo** [comment]
When the healthcheck still created volumes in the most brute way, the DAL got out of sync quite fast. When Ops is running this check every 5 mins and 1/10-1/20 had failed (just saw the remnants, not the actual cause), this can escalate fast and a sync would but optimal.

**Comment by wimpers** [comment]
@khenderick please make sure there is an escalation path in place.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Sync job has been scheduled to run every hour 24/7/365 at half past the hour
When a vDisk is created or removed due to inconsistencies, we report: OVS_WARNING: \<message\>

https://github.com/openvstorage/framework/pull/1577 --> openvstorage-2.8.2-dev.1491303859.9ee8628

**Comment by wimpers** [comment]
@matthiasdeblock @jeroenmaelbrancke  please create the necessary rules to monitor this event in check_MK(?) so this doesn't go below the radar.

**Comment by kvanhijf** [comment]
Already created a ticket in monitoring repository, but forgot to link it, so here it is
https://github.com/openvstorage/openvstorage-monitoring/issues/129

PS: Code is still on our develop branch
