### ISSUE TITLE
/mnt/vmstore cleanup after vm system removal

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1511]
On a new testing environment under /mnt/vmstor/ the directories are not deleted when the vm are destroyed.
This is causing a slow response on the directory even on basic commands
root@stor-01:/mnt/vmstor# time ls -Fal | wc -l
2176
real	0m5.874s
user	0m0.040s
sys	0m0.096s
root@stor-01:/mnt/vmstor#
Could the api interface of ovs delete the directory as well when the virtual machine is destroyed ?

**Comment by wimpers** [comment]
Add API to cleanup directory or a parameter

**Comment by matthiasdeblock** [comment]
For your information:

When GIG is executing their tests they create / remove / create / ... a lot of vdisks. As they create the vdisks with a directory structure and just remove the vdisk and not the directory, you get, after some time, a large filesystem metadata DB which can cause a freeze of a 'ls' of the mountpoint (and maybe other issues as well).

This week, a GIG environment had around 65k leftovers in the filesystem metadata db. This caused the slow 'ls' of the mountpoint. I removed the leftovers (script ran about 8 hours) but this caused a lot of data on the DB disk which got full on 2 of the 3 nodes (I guess you can think what happened with that env.). The arakoon didn't had the time to collapse due to the large amount of generated tlx files.

**Comment by kvanhijf** [comment]
As discussed with @redlicha, this is an issue which should be addressed by letting the framework use the voldrv API, but due to lack of any exposed functionality in the volumedriver to do these kind of actions, we need to wait for the volumedriver to expose this.
@redlicha please notify us when it has been exposed (unlink in the FileSystemMetadataClient)

**Comment by redlicha** [comment]
StorageRouterClient.unlink now also allows the removal of empty directories. Available in the latest dev build on the 16.04 repo's unstable, with flavours to follow.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
No API as requested has been provided, instead the framework does the cleaning
Eg: 
/mnt/vpool1/map/submap/vd1.raw
/mnt/vpool1/map/vd2.raw
/mnt/vpool1/map/vd3.raw

When deleting vd1.raw, `submap` directory will be removed too, because its the last vdisk in that directory
When deleting vd2.raw, `map` directory will not be removed, because another vdisk is still in the directory

https://github.com/openvstorage/framework/pull/1592 --> openvstorage-2.8.2-dev.1492678359.45b7423
