### ISSUE TITLE
vPool shrink failed due to "Operation canceled" on MDS client(s)

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1530]
On the OVH environment, we saw a vPool shrink fail:
1. For every vDisk that has an MDS entry (either master or slave) on the to be removed StorageDriver, the MDS is reconfigured (if required) blacklisting that StorageDriver;
2. The MDS service(s) are cleaned up

A few vDisks in step (1) did fail due to an `Operation canceled` error, causing step (2) to fail. Step 2 is considered "critical" and will cause the vPool to get in `FAILURE` state. This means the MDS should be cleaned up manually before the vPool can be set to `RUNNING` again.

A few stacktraces of the `Operation canceled`:

```
Mar 16 12:25:27 ovs04 celery[116189]: Traceback (most recent call last):
Mar 16 12:25:27 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 989, in remove_storagedriver
Mar 16 12:25:27 ovs04 celery[116189]:     excluded_storagerouters=[storage_router] + storage_routers_offline)
Mar 16 12:25:27 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 621, in ensure_safety
Mar 16 12:25:27 ovs04 celery[116189]:     client.create_namespace(str(vdisk.volume_id))
Mar 16 12:25:27 ovs04 celery[116189]: RuntimeError: Operation canceled
```

```
16 12:22:47 ovs04 celery[116189]: Traceback (most recent call last):
Mar 16 12:22:47 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 989, in remove_storagedriver
Mar 16 12:22:47 ovs04 celery[116189]:     excluded_storagerouters=[storage_router] + storage_routers_offline)
Mar 16 12:22:47 ovs04 celery[116189]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 642, in ensure_safety
Mar 16 12:22:47 ovs04 celery[116189]:     client.set_role(str(vdisk.volume_id), MetadataServerClient.MDS_ROLE.SLAVE)
Mar 16 12:22:47 ovs04 celery[116189]: RuntimeError: Operation canceled
```

**Comment by khenderick** [comment]
@redlicha, do you know what might be the cause of this?

**Comment by redlicha** [comment]
`Operation canceled` indicates a timeout on the client side (configurable in the `MDSClient` ctor, default value is 20 secs). For the `set_role` call this is expected behaviour if a volume's namespace with many TLogs is specified as the periodic background task that replays TLogs has to finish first.
For the `create_namespace` this is however unexpected - https://github.com/openvstorage/volumedriver/issues/286

**Comment by khenderick** [comment]
If we created a namespace, we don't have to set the role to slave for that namespace on that client. So better keep track of "fresh" namespaces so we can prevent having to set the role.

**Comment by redlicha** [comment]
`get_role` should not take long either, i.e. it does not have to wait for the background task.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1781 --> openvstorage-2.10.0-dev.1506000428.be2e052

**Comment by kvanhijf** [comment]
* create_namespace  
  * If this would fail, no changes will be propagated to the volumedriver, thus this should result in no changes anywhere (not voldr, not in model)
  * Now we only perform a create_namespace when a vDisk will be served by a MDS, which it wasn't served by previously
  * In case this fails, all previously created namespaces will be deleted to prevent from storage leaks
  
* set_role
  * In case this fails, the ensure_safety will throw an error for the vDisk it was processing.
  * However sync with reality has been moved to be executed BEFORE the set role, because the sync with reality takes the current config from the StorageDriver and puts it in the model as such. Only taking the order of MDSes returned into account and not the roles at that time.
  * A CRITICAL log entry is recorded in such an event. Then its up to OPS to verify why it failed and if a manual action is required
  * Also we do not execute set_role to SLAVE if the role is already SLAVE at that point, which was the case in the old code

* Timeouts
  * Additionally its now possible to introduce timeouts for both StorageDriver Client actions in ensure_safety and MDS Client actions
    * ovs/vpools/<vpool_guid>/mds_config|mds_client_connection_timeout (default 120s)
    * ovs/vpools/<vpool_guid>/mds_config|sr_client_connection_timeout (default 300s)
  * MDS timeout is used when creating namespaces, listing namespaces, set and get role
  * SR timeout is used to update the actual MDS configuration
