### ISSUE TITLE
Integrate statsmonkey into framework

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1573]
As discussed and agreed upon, statsmonkey should be moved from the operations monitoring repo to the framework repo

This will allow:
- to avoid update issues as observed on ovh
- to pre-validate / test statsmonkey/framework combination before installation
- recycle/optimize  stats data already available via the framework

**Comment by wimpers** [comment]
Should also tackle https://github.com/openvstorage/openvstorage-monitoring/issues/132 turning the statsmonkey service into a celery task.

**Comment by kvanhijf** [comment]
Added priority critical to it because the presence of the statsmonkey on an environment WILL BREAK the update.
When statsmonkey relies on imports which have been changed in a new release and the update is started, re-loading the statsmonkey module will result in the update failing.
When the statsmonkey would no longer be a stand-alone file, this would no longer be an issue, since the update would also update the statsmonkey module

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1825 --> openvstorage-2.11.1-dev.1508761354.9c74fe5
https://github.com/openvstorage/alba-asdmanager/pull/296 --> openvstorage-sdm-1.11.0-dev.1508761294.96200d1
https://github.com/openvstorage/framework-alba-plugin/pull/512 --> openvstorage-backend-1.11.0-dev.1508761150.9969129
https://github.com/openvstorage/framework-extensions/pull/41 --> openvstorage-extensions-0.3.0-dev.1508761214.8d2b18d
https://github.com/openvstorage/iscsi-manager/pull/39 --> iscsi-manager-0.3.0-dev.1508761263.5dc35ef

**Comment by kvanhijf** [comment]
Statsmonkey can be configured via
'Administration dropdown' --> 'Support' page --> 'Support Settings' section

When enabling statsmonkey, credentials and other information will be prompted for regarding where/how the stats need to be stored

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
