### ISSUE TITLE
multiple arakoon collapse tasks running on same node

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1586]
After restarting the ovs-workers we see multiple arakoon collapse tasks running on a node.
```
root@ovs03:~# ps aux | grep collapse
ovs       37677 25.2  0.0 494284 239644 ?       Dsl  16:15   7:11 arakoon --collapse-local SNmoxveFD0RethGN 2 -config arakoon://config/ovs/arakoon/ssdBackend-nsm_4/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
ovs      101556 33.0  0.0 236352 46232 ?        Rl   16:43   0:00 arakoon --collapse-local SNmoxveFD0RethGN 2 -config arakoon://config/ovs/arakoon/nvmebackend-nsm_14/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
root     101565  0.0  0.0  16364   984 pts/0    S+   16:43   0:00 grep --color=auto collapse
```

**Comment by khenderick** [comment]
Issue is that our `_ensure_single` doesn't survive a restart of the workers. The ensure single adds a key in arakoon to "lock" the task, but if for some reason the worker would be killed, this lock would not be removed. That is why a start of the workers will wipe out this key. This however is an issue if the workers on only one node are restarted since this might result in a task running twice after all.

Possible solution: Add the task identifier as (part of the) value. When a worker is started, it can then retrieve the identifier and check whether that task is still running or not. If so, it can just leave the key in place. If not, it can be removed.

**Comment by khenderick** [comment]
This will not only happen to the arakoon collapses, but can happen to all (scheduled) tasks: scrubbing, snapshotting, creating arakoon clusters, ...

**Comment by khenderick** [comment]
#1594 -> openvstorage-2.8.2-dev.1492681177.e9d9c3a
