### ISSUE TITLE
Allow a different nsm maxload for fragment/block namespaces

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1620]
Currently the limit of namespaces per NSM cluster is 75.  for block cache and fragment cache name namspaces this limit could be higher as they typically contain less fragments.

**Comment by wimpers** [comment]
It would be nice if these  could be a variable in the ovs config DB and make it dynamically reconfigurable.

**Comment by khenderick** [comment]
@wimpers, that's a bit incorrect. The `maxload` is set to `75`, which means that a new NSM will be set up or requested once more than 75 *percent* of its capacity is used. The capacity can be configured at runtime without any restarts and can be a different value for every NSM cluster. It's stored in the model and the setting is available since our first version.

**Comment by wimpers** [comment]
@khenderick basically we can do already what we want (allow more namespaces per NSM in case of an SSD backend )?

**Comment by khenderick** [comment]
We can configure the amount of namespaces per NSM cluster and the threshold from which it should already prepare another one.

**Comment by wimpers** [comment]
Already part of the product.
