### ISSUE TITLE
Remove  Remote Access functionality

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1651]
Since the Remote Access no longer is working/needed:
- Remove  Remote Access code
- Remove "Remote Access enabled" in the GUI

**Comment by khenderick** [comment]
It is working. But if not needed, we can indeed remove it.

**Comment by saelbrec** [comment]
Let's give this some more thought before removing, it's not because we think it is useless for a certain type of installs tomorrow that the day after another opportunity is around the corner where we need to put it back in.
What's wrong with keeping it in and disabled for the installs that don't want to make use of it ?

**Comment by wimpers** [comment]
Re-open if needed.
