### ISSUE TITLE
Change storage router before the ips are loading result in wrong ip (create vpool)

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1658]
When changing the storage router while the ips are still loading result in a wrong list of ips.

Before the ips are loaded:
![wrong_ip](https://cloud.githubusercontent.com/assets/2900612/26822563/c430bc5c-4aaa-11e7-9479-ad18efb83464.png)

Waiting until the ips are loaded:

![correct_ip](https://cloud.githubusercontent.com/assets/2900612/26822567/c7021e58-4aaa-11e7-83da-1507d44714aa.png)

**Comment by JeffreyDevloo** [comment]
Taking this up with my edit-vpool changes. Have to change certain aspects about the add, might as well take this up.

**Comment by JeffreyDevloo** [comment]
Fixed by 
- #1821 
- https://github.com/openvstorage/framework-iscsi-plugin/pull/34
- https://github.com/openvstorage/framework-extensions/pull/63
- https://github.com/openvstorage/framework-alba-plugin/pull/534

Packaged in:
 - openvstorage_2.12.0-dev.1518011126.4cee8bc-1_amd64.deb
 - openvstorage-backend_1.12.0-dev.1518011188.e274a3d-1_amd64.deb
 - openvstorage-extensions_0.4.0-dev.1518010323.90e5a68-1_amd64.deb
 - openvstorage-iscsi-plugin_0.4.0-dev.1518011220.53302ad-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
