### ISSUE TITLE
Re-use connection for fragment cache when extending vpool

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1678]
openvstorage 2.9.5-1

When extending a vpool you do not have the opportunity to re-use a connection you have used before on the fragment cache. 

The block cache does have this option:
![screenshot_2017-06-09_10-21-38](https://user-images.githubusercontent.com/14923932/27086640-0dd558f6-5053-11e7-8e70-3bc9a830caac.png)

It would be very useful to have this for the fragment cache as well.

**Comment by wimpers** [comment]
@matthiasdeblock just to make sure, this is just to make the OPS life easier. You can configure everything correct as needed, right?

**Comment by matthiasdeblock** [comment]
Yes, everything works but it's just a lot of copy/paste work...

**Comment by JeffreyDevloo** [comment]
ლ(ಠ益ಠლ) use the api client to avoid repetitive tasks :P

**Comment by JeffreyDevloo** [comment]
Fixed by 
- #1821 
- https://github.com/openvstorage/framework-iscsi-plugin/pull/34
- https://github.com/openvstorage/framework-extensions/pull/63
- https://github.com/openvstorage/framework-alba-plugin/pull/534

Packaged in:
 - openvstorage_2.12.0-dev.1518011126.4cee8bc-1_amd64.deb
 - openvstorage-backend_1.12.0-dev.1518011188.e274a3d-1_amd64.deb
 - openvstorage-extensions_0.4.0-dev.1518010323.90e5a68-1_amd64.deb
 - openvstorage-iscsi-plugin_0.4.0-dev.1518011220.53302ad-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
