### ISSUE TITLE
Do not continue shrinking a vpool when the mds cannot be removed

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1738]
### Problem description
On gig we saw an issue where ensuring the safety for certain disks failed because `vdisk.storagedriver_client.update_metadata_backend_config` took longer than 5 seconds.
Due to this the junction from the mds_service still has entries but the shrinking will continue.

Later in the code (mds checkup), the mds_services are fetched again (this service did not get removed because of leftover junctions) and tries to fetch the already deleted storagedriver.

**Comment by wimpers** [comment]
Is this related to  https://github.com/openvstorage/framework/issues/1530 or is this another area where the shrink vPool might get stuck.

**Comment by kvanhijf** [comment]
Its a different path in the MDS configuration. So we need both tickets, but they can be fixed in 1 go obviously

**Comment by matthiasdeblock** [comment]
GIG and Nuvolat are running into this issue. There is workaround but there should be a fix ASAP.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1780 --> openvstorage-2.10.0-dev.1505983462.2b7be45

The MDS checkup and ensure_safety have been rewritten a bit. Less errors should be raised now. However in the case it would still occur, the shrinking of the vPool is stopped before anything is actually done. The vPool will also be automatically be put back in RUNNING status. This is purely because error messages are now displayed in the GUI indefinitely, so if anything goes wrong you will be able to see the message
