### ISSUE TITLE
global remote backend not available in add vpool

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1802]
Only be1 & be2 are available when adding a new vpool
![screenshot from 2017-09-27 18-05-14](https://user-images.githubusercontent.com/15377625/30924267-8a1a02aa-a3ae-11e7-9539-772010265747.png)
while there should also be a global backend available...
![screenshot from 2017-09-27 18-06-39](https://user-images.githubusercontent.com/15377625/30924327-ba21b182-a3ae-11e7-9614-054e2802f821.png)

@kvanhijf knows more details about the underlying cause

**Comment by kvanhijf** [comment]
This issue is only applicable in the following case:
Environment on which the vPool is being created/extended has the latest unstable code (2.10.0 atm)
Environment from which a GLOBAL Backend is being retrieved runs older code (2.9.6 or lower)

The reason for this issue is because the latest code (2.10.0) retrieves the information of the remote GLOBAL backend and verifies if its size > 0. The remote GLOBAL backend however running on 2.9.6 code uses asd-multistatistics for this information which always returns 0 for a GLOBAL Backend
Thus all GLOBAL backends are filtered out because they'll always report size 0.

In older code, we used to check on the amount of OSDs linked to a backend, which did not have this problem

**Comment by domsj** [comment]
Sounds like a user issue? @dejonghb should've just updated all nodes of all his clusters to the same version at the same time?!? :smile:

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1804 --> openvstorage-2.11.0-dev.1506597359.f602de3

**Comment by kvanhijf** [comment]
Included in release https://github.com/openvstorage/framework/releases/tag/2.10.1
