### ISSUE TITLE
Add syslogidentifier to the systemd service file

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#2099]
This should solve https://github.com/openvstorage/dev_ops/issues/163

**Comment by JeffreyDevloo** [comment]
Looking into systemd: the `syslogidentifier` might explain why we are seeing the current logs on the rsyslog server.
There might be a rule we can adjust to always select the unitfile name instead of the name of the executable within the service

```
SyslogIdentifier=

    Sets the process name ("syslog tag") to prefix log lines sent to the logging system or the kernel log buffer with. If not set, defaults to the process name of the executed process. This option is only useful when StandardOutput= or StandardError= are set to journal, syslog or kmsg (or to the same settings in combination with +console) and only applies to log messages written to stdout or stderr.
```

Further looking into it:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html Systemd has specifiers. These are arguments which are resolved after daemon-reload.
The one we might need is %N which is the unit-file name.

Make sure that the rsyslog can handle long names.

**Comment by JeffreyDevloo** [comment]
All templates should be updated with `SyslogIdentifier=%N` to resolve this issue.

**Comment by sjovdnbos** [comment]
#### Fixed by:
https://github.com/openvstorage/framework/pull/2119
https://github.com/openvstorage/iscsi-manager/pull/66
https://github.com/openvstorage/alba-asdmanager/pull/336
https://github.com/openvstorage/framework-extensions/pull/142

#### Package information:
openvstorage-2.13.0-dev.1531396881.e7fafc2
iscsi-manager-0.5.0-dev.1531397013.b21aff4
openvstorage-sdm-1.13.0-dev.1531397044.6031559
openvstorage-extensions-0.4.2-dev.1531397082.c5f7967

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
