### ISSUE TITLE
some vdisks' DTLs in red after remove an offline node 

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2198]
i conducted a test on removing an offline node by using `remove node <ip>` command.  It works fine!

However, I found DTL states  of some vdisks' are in red.  I also found the preset didn't switch to an usable policy for two nodes (only one alba-asd per node).  After i manually switched the policy order by moving 2-dup ahead, the DTL states became green.  The policies I defined : (1, 1, 1, 2), (1, 2, 1, 3).  Not sure if this operation is related to DTL state.

_Originally posted by @yongshengma in https://github.com/openvstorage/framework/issues/2197#issuecomment-424200708_

**Comment by yongshengma** [comment]
Then I re-installed and setup the third node.  'ovs setup' went well except that an error was popped at the end.

```
Select the port to be used for the ASDs [8600]: 
- Starting watcher service
+++++++++++++++++++++++++++++++++++++
+++  ASD Manager setup completed  +++
+++++++++++++++++++++++++++++++++++++
Exception in thread Thread-29 (most likely raised during interpreter shutdown):Exception in thread Thread-23 (most likely raised during interpreter shutdown): 

```
Then I did necessary role assignment to hard drives.

Then I goto backend to add this ASD node, but it pops out window saying "Replace node" and "`Node YfW7EpsyoP2VR0E0wpe07GpysyHBxkzm with IP 192.168.2.23 already exists and will be replaced by this node when proceeding.`"   . 192.168.2.23 was the node that I have removed and then re-installed and setup.

Then I initialize alba and claim asd of this node, and each step looks ok.  But there is still the plus line of this node.  
![image](https://user-images.githubusercontent.com/17973897/45998109-5535f780-c0d4-11e8-9f2e-1a9b900ec9d5.png)

**Comment by JeffreyDevloo** [comment]
HI @yongshengma 
The error is known and benign: https://github.com/openvstorage/framework/issues/2014
The managers register themselves within the configuration arakoon. When removing a node which is offline, this configuration entry is never cleaned up.
You won't be able to add the node since the credentials have changed because of a reinstall.
You can remove the old asdmanager entry using:
```
from ovs.extensions.generic.configuration import Configuration
node_id = INSERT NODE ID
asd_node_location = '/ovs/alba/asdnodes/{0}'.format(node_id)
if Configuration.dir_exists(asd_node_location):
    Configuration.delete(asd_node_location)
```

I'll have to dig around for your DTL state being red
Edit: 
The DTL is in red, meaning 'checkup_required'. The DTL has lost one of the nodes within its config. The reinstall of a node wiped all the services.
Every now and then, the Framework syncs all vdisks on the environment and it will detect that a storagerouter was reinstalled. It will change all vdisk related configs to work with 2 nodes instead of 3 (node_distance_map, dtl config, ...)
The preset availability won't affect the DTL. It will cause the volumedriver to choke
Edit 2:
Both preset should be working with 2 nodes with both only 1 asd. Not sure why the Framework marked them as unusable. Perhaps an ASD was in the error state?

**Comment by yongshengma** [comment]
It works.  Thanks!

**Comment by JeffreyDevloo** [comment]
Closing the ticket down as this works as it should:
- Removing a node brings down a DTL host
- Framework notices it, says DTL requires a checkup
- Framework schedules a DTL checkup at some point
- DTL is fine again (2 hosts instead of 3)
