### ISSUE TITLE
docker build env for arakoon

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#412]
in https://github.com/openvstorage/docker_arakoon

get inspiration from e.g.
https://github.com/Jumpscale/docker_influxdb

what
- start from ubuntu 15.10 SSH supported docker
- build using https://hub.docker.com/
- create documentation to explain where binaries are

steps to do
- install all build requirements
- download required sourcecode
- build server & client components
- build python client 2.7 & 3.5 support !!!

this is basis for dockers as used in docker test/development environment
- see https://github.com/openvstorage/openvstorage/blob/master/Specs/DockerEnv.md

for more info how to build the dockers see
- see https://github.com/openvstorage/openvstorage/blob/master/Specs/DockerBuilders.md

**Comment by toolslive** [comment]
Both Arakoon and Alba have been using docker on jenkins for continuous integration since Q3 2015.

The recipes can be found here 
- Arakoon: https://github.com/openvstorage/arakoon/blob/1.9/docker/arakoon_debian/Dockerfile
- Alba : https://github.com/openvstorage/alba/blob/master/docker/alba_debian_jenkins/Dockerfile

However, these do way more than just build Arakoon or Alba. For example, they also include installing etcd and the (development) volumedriver packages for integration tests, or older versions to allow us to validate backward compatibility. 
If you want docker images for demos, those images should probably not include the build toolchain.
