### ISSUE TITLE
disk/role configuration should happen in parallel

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#514]
Currently when you configure roles on your cluster, every configuration happens in serial mode. 

This means for even small clusters like 4 nodes, you configure at least 12 - 16 disks that takes each 1.5 - 2 minutes to complete. 

Worst case scenario, you lost 30 minutes for 4 nodes.

**Comment by wimpers** [comment]
@pploegaert please investigate why it takes so long.

**Comment by khenderick** [comment]
@wimpers, I don't think the point is that assigning a role to a disk can take 1.5 to 2 minutes (we're starting an async task on celery, wait for it to get picked up, it partitions the disk, makes a filesystem, then assign roles, makes sure everything is back in sync in the model, ...).

I think the issue here is that all disks are processed sequentially, while we most likely can figure out a way to run all disk role assignments in parallel.

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/framework/issues/696 so closing this one down.
