### ISSUE TITLE
public/private key pair locations & generation

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#545]
Around https://github.com/openvstorage/framework/blob/master/ovs/lib/setup.py#L305 the code expects to find keys in the hardcoded '/opt/OpenvStorage/.ssh' path.

This /opt/OpenvStorage path is expected to be the homedir of the ovs user in https://github.com/openvstorage/framework/blob/master/scripts/install/openvstorage-core.postinst.py#L107 which user might have been created (if not present on the system yet) via the preinst script of the openvstorage-core package.

In case the user is already present on the system and has another homedir, things will go wrong.

On a side note: creating the keys should be done in the setup phase, not when the package is installed. In case one creates an image (eg. docker / virtual machine) with all packages installed and the images are re-used all key pairs in the images will be the same...

**Comment by wimpers** [comment]
We will move to ovs setup.
Working around an existing ovs user will not be tackled as it is in the documentation that no such user may exist.

**Comment by khenderick** [comment]
An update on the current state.

In the package pre-install scripts, the `ovs` user is created if it doesn't yet exist. If created, it's home directory will be `/opt/OpenvStorage/`. In the post-install script, SSH keys will be generated in the `ovs` and `root` user's home directory if they don't yet exist.

The setup however exchanges keys between the `ovs` and `root` users on across all nodes because it is required at this moment. The current issue is that the setup _assumes_ the ssh keys to be in `/opt/OpenvStorage/.ssh/` and `/root/.ssh/` instead of using `~/.ssh/` for both users.

**Comment by khenderick** [comment]
Todo:
* Move key generation to the setup
* Use `~/.ssh/` when keys are being exchanged.

Side effect: it should not matter whether `/opt/OpenvStorage/` is the `ovs` user's home directory or whether an `ovs` user was created beforehand. The fact that it was documented as "the `ovs` user should not exist" was merely a workaround for the pending issue stated in my earlier comment.

**Comment by khenderick** [comment]
Fixed in #1374, packaged on dev openvstorage-2.7.11-dev.1485422228.1396dc5

**Comment by khenderick** [comment]
openvstorage-2.7.11.1
