### ISSUE TITLE
vPool Cache investigation / enhancements

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#669]
This issue is 2-fold:
1. If the readcache is disabled for a vPool, will there be a file created on the filesystem or not?  This might be required when readcache behavior is overruled for a specific vDisk
2. When readcache is disabled for a vPool, the GUI still asks for a size to provide for the readcache. This becomes obviously obsolete in such scenario

**Comment by khenderick** [comment]
After implementation, the vPool wizard will not ask for read cache size if no cache is being configured. Moreover, a partition with READ role is not required. In the mean time, the vPool wizard was restructured again so the entire flow is more logical, makes more sense and validation is executed when expected.

If no read cache was requested, no `read.dat` will be created.

**Comment by khenderick** [comment]
Resolved by #729

**Comment by deepshirsath** [comment]
**_Open vStorage: 2.7.1-fargo.2-1_**
- The vPool wizard now not asking for read cache size if no cache is being configured/selected. 
- If no read cache was requested, no read.dat will be created. (fixed in #683 )

Also 

Read role is required with AAA and no-cache strat on volumedriver #789 (https://github.com/openvstorage/framework/issues/789) is raised and open for still read role check is present while creating vpool.
