### ISSUE TITLE
Integrate new scrubber workflow

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#727]
Integrate new scrubber workflow, see openvstorage/volumedriver#53

**Comment by khenderick** [comment]
Labels and milestone set from openvstorage/volumedriver#53

**Comment by kinvaris** [comment]
Adding label SRP at command of @saelbrec

**Comment by kvanhijf** [comment]
As i have understood from talking to @redlicha . We should implement the following.
On the node where the scrubbing will be executed, a proxy for each vpool with vdisks to scrub has to be present.
Eg:
node1 - vpool1 - no scrub role
node2 - vpool1 - scrub role
node3 - vpool2 - no scrub role
Scrubbing vDisks of vPool1 on node2 does not require any changes, since we deploy a proxy on every node where a vPool is running, but scrubbing vDisks of vPool2 will be impossible on node2, since node2 does not have a proxy pointing to vPool2 (only to vPool1)

Another example (dedicated scrub server):
node1 - vpool1 - no scrub role
node2 - vpool1 - no scrub role
node3 - vpool2 - no scrub role
node4 - no vpool - scrub role
In this case we should deploy a proxy pointing to vPool1 and a proxy pointing to vPool2 on node4 for the scrubbing to be able to be executed successfully

@khenderick, @saelbrec 
To be discussed:  When exactly do we deploy such (potential) additionally required proxies

Potential solutions:
- Option1: Require each vPool to have at least 1 StorageRouter with a SCRUB role
  *\* This would imply that when creating the vPool, the node on which it is being created should have the SCRUB role, which we could enforce via the GUI
- Option2: Add proxies whenever needed in the scheduledtask reponsible for the scrubbing using some sort of alba_proxy_checkup method
- Option3: ???

**Comment by kvanhijf** [comment]
In the new implementation, we deploy an ALBA proxy on each StorageRouter if they have a SCRUB role regardless if they already run a proxy for the vPool

Example:
node1 - vpool1 - scrub role
node2 - vpool1 + vpool2 - no scrub role
node3 - vpool1 + vpool3 - scrub role
node4 - vpool3 - no scrub role

Scrub vdisk of vpool1 on node1 -->a proxy will be deployed
Scrub vdisk of vpool2 --> can be executed on node1 or node3 and in each case a proxy will be deployed on the respective node
Scrub vdisk of vpool3 --> can also be executed on node1 or node3

The code responsible for deploying a proxy will also remove the proxy again once all scrubbing on that node has been completed (or failed)

**Comment by kvanhijf** [comment]
openvstorage-2.7.3-rev.4036.2154ffe

**Comment by kvanhijf** [comment]
@QA: To generate scrub work for vDisks, you can use a command like this on a .raw vdisk
`dd if=/dev/zero of=/mnt/vpool/disk1.raw bs=1M count=20 conv=notrunc`
After a 'dd' create a snapshot --> This should already be enough to have generated scrub work

Then have random number of SCRUB roles and invoke scrubbing (ScheduledTaskController.execute_scrub() and verify through the logging (/var/log/ovs/lib.log) that each vDisk can potentially be scrubbed on any StorageRouter with a scrub role independent of the vPool is extended on that StorageRouter

**Comment by kinvaris** [comment]
PASSED: Verified in CI tests & https://github.com/openvstorage/framework/issues/538
