### ISSUE TITLE
Extend the storage router status to incorporate disk status

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#775]
Currently a disk which is having the DB role might be dead but the Storage Router will still show green (as Arakoon runs distributed and the slave metadata server will pick up). It would be handy that if the DB role  or another disk fails in the storage router that it would be shown in the GUI (storage router orange, phusical disk red).

Note that both OVS healthcheck and OVS monitoring would pick this failure up.

**Comment by khenderick** [comment]
Fixed by #1003, packaged in openvstorage-2.7.4-rev.4090.0b617c3

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup latest cluster
- Added disk roles
- Removed disk with DB role
- Rescanned disks
- Verified storagerouter status

### Output
![selection_067](https://cloud.githubusercontent.com/assets/17570109/20484299/d877bade-aff6-11e6-85f3-170a796a6440.png)

### Test result
Storagerouter was marked as failure due to the missing disk. Test passed.
### Setup
- Hyperconverged cluster
- 2 vpool (extended to all nodes)
- 3 backends (mybackend01, mybackend02 and global backend)

#### Packages
- openvstorage                         2.7.6-rev.4320.8c4fb99- amd64                   openvStorage
- openvstorage-backend                 1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin
- openvstorage-backend-core            1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.6-rev.4320.8c4fb99- amd64                   openvStorage core
- openvstorage-hc                      1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin HyperConverged
- openvstorage-sdm                     1.6.6-rev.445.4216f7e-1 amd64                   Open vStorage Backend ASD Manager
- openvstorage-webapps                 2.7.6-rev.4320.8c4fb99- amd64                   openvStorage Web Applications
