### ISSUE TITLE
Port ranges for vpools should be reserved

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#923]
If you have vpool A and vpool B and 2 storagerouters.

Situation:
Setting up vpool A then vpool B on storagerouter 1
Setting up vpool B then vpool A on storagerouter 2

As seen from compute node perspective, the ports for vpool A will be different on storagerouter 1 compared with storagerouter 2.

As a solution, you could reserve some ports only for a certain vpool on a whole cluster.
E.g.

vpool A: 26200 - 26206
vpool B: 26210 - 26216

In this case, the user would have to know that those ports can't be `busy` on the nodes he wants to deploy a certain vpool.

Another solution for this problem is to provide a `pre-scan` in the GUI with a warning that some required ports are already claimed for that storagerouter. In this case the user has the option to proceed, then a new range will be determined for the whole vpool cluster and adjusted for that vpool.
This probably requires the volumedriver to restart, unless it is possible to reload the config at runtime.

**Comment by khenderick** [comment]
This is (more or less) like it used to be in the past. It was changed to the current flow because:
- It requires (as @kinvaris states) a pre-reservation of ports on all nodes that might in the future want to run the vpool.
- It's more work when a vPool is created since only ports free on all nodes can be selected)
- More prone to failure (ports are determined upfront, now the ports are selected right before they will be used)

Wrt the solutions suggested by @kinvaris:
- We can't guarantee the above, so when extending the vPool it might be impossible to do so for certain nodes (that don't have the ports free anymore)
- Ports are not dynamically reconfigurable, so it would require the complete vPool to go down. Another possibility is that we allow extend but then again select other ports (but that defeats the very purpose of this ticket)

From what I understand, this ticket was created because at this moment failover assumes identical ports on all nodes. However, as far as I understand, as soon as edge HA is finished and integrated, the ports won't matter anymore.

**Comment by khenderick** [comment]
The usecase for this request is quasi obsolete: #895 introduces edge HA.

**Comment by wimpers** [comment]
It was decided from the beginning that we would not require the same ports across all nodes.
